package Modelo1;
// Generated 13/04/2016 11:24:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import logic.HibernateUtil;
import org.hibernate.Session;

/**
 * Prestador generated by hbm2java
 */
public class Prestador  implements java.io.Serializable {


     private int idUsuario;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String correo;
     private String telefono;
     private byte[] fotoU;
     private String contrasenya;
     private int cuartosDisponibles;
     private Set<TieneContratoU> tieneContratoUs = new HashSet<TieneContratoU>(0);
     private Set<TieneCuarto> tieneCuartos = new HashSet<TieneCuarto>(0);
     private Session session;
     private String contrasenyav;
     private String paisU;
     private String estadoU;
     private String delegacionU;
     private String CodigoPostalU;
     private String coloniaU;
     private String calleU;

    public String getContrasenyav() {
        return contrasenyav;
    }

    public void setContrasenyav(String contrasenyav) {
        this.contrasenyav = contrasenyav;
    }

    public String getPaisU() {
        return paisU;
    }

    public void setPaisU(String paisU) {
        this.paisU = paisU;
    }

    public String getEstadoU() {
        return estadoU;
    }

    public void setEstadoU(String estadoU) {
        this.estadoU = estadoU;
    }

    public String getDelegacionU() {
        return delegacionU;
    }

    public void setDelegacionU(String delegacionU) {
        this.delegacionU = delegacionU;
    }

    public String getCodigoPostalU() {
        return CodigoPostalU;
    }

    public void setCodigoPostalU(String CodigoPostalU) {
        this.CodigoPostalU = CodigoPostalU;
    }

    public String getColoniaU() {
        return coloniaU;
    }

    public void setColoniaU(String coloniaU) {
        this.coloniaU = coloniaU;
    }

    public String getCalleU() {
        return calleU;
    }

    public void setCalleU(String calleU) {
        this.calleU = calleU;
    }
    public Prestador() {
    }

	
    public Prestador(int idUsuario, String nombre, String apellidoPaterno, String apellidoMaterno, String correo, String telefono, String contrasenya, int cuartosDisponibles) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.correo = correo;
        this.telefono = telefono;
        this.contrasenya = contrasenya;
        this.cuartosDisponibles = cuartosDisponibles;
    }
    public Prestador(int idUsuario, String nombre, String apellidoPaterno, String apellidoMaterno, String correo, String telefono, byte[] fotoU, String contrasenya, int cuartosDisponibles, Set<TieneContratoU> tieneContratoUs, Set<TieneCuarto> tieneCuartos) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.correo = correo;
       this.telefono = telefono;
       this.fotoU = fotoU;
       this.contrasenya = contrasenya;
       this.cuartosDisponibles = cuartosDisponibles;
       this.tieneContratoUs = tieneContratoUs;
       this.tieneCuartos = tieneCuartos;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public byte[] getFotoU() {
        return this.fotoU;
    }
    
    public void setFotoU(byte[] fotoU) {
        this.fotoU = fotoU;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }
    public int getCuartosDisponibles() {
        return this.cuartosDisponibles;
    }
    
    public void setCuartosDisponibles(int cuartosDisponibles) {
        this.cuartosDisponibles = cuartosDisponibles;
    }
    public Set<TieneContratoU> getTieneContratoUs() {
        return this.tieneContratoUs;
    }
    
    public void setTieneContratoUs(Set<TieneContratoU> tieneContratoUs) {
        this.tieneContratoUs = tieneContratoUs;
    }
    public Set<TieneCuarto> getTieneCuartos() {
        return this.tieneCuartos;
    }
    public String regDir(){
       session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Modelo1.DireccionUsuario e = new Modelo1.DireccionUsuario(this.idUsuario, this.paisU,this.estadoU,this.delegacionU,Integer.parseInt(this.CodigoPostalU),this.calleU,this.coloniaU);
        if(e != null){
            session.save(e);
            session.getTransaction().commit();
            session.close();
        }else{
            FacesContext.getCurrentInstance().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_ERROR, "Datos incorrectos", null));
            return "RegistroEstudiante";
        }
    
        return "Principal.xhtml";
    }
    public void setTieneCuartos(Set<TieneCuarto> tieneCuartos) {
        this.tieneCuartos = tieneCuartos;
    }
    
    /**
     *
     * @return
     */
    public String rD() {
        session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Modelo1.DireccionUsuario e = new Modelo1.DireccionUsuario(this.idUsuario, this.paisU,this.estadoU,this.delegacionU,Integer.parseInt(this.CodigoPostalU),this.calleU,this.coloniaU);
        if(e != null){
            session.save(e);
            session.getTransaction().commit();
            session.close();
        }else{
            FacesContext.getCurrentInstance().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_ERROR, "Datos incorrectos", null));
            return "RegistroEstudiante";
        }
    
        return "Principal.xhtml";
    }
    
    public String registrar() {
        int idNew =100;
        session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Modelo1.Prestador c = (Modelo1.Prestador) session.get(Modelo1.Prestador.class, idNew);
        while(c != null){
            idNew++;
            c = (Modelo1.Prestador) session.get(Modelo1.Prestador.class, idNew);
        }
        this.idUsuario =idNew;
         Modelo1.Prestador e = new Modelo1.Prestador(this.idUsuario,this.nombre,this.apellidoPaterno,this.apellidoMaterno, this.correo,this.telefono,this.contrasenya,0);
        if(e != null){
            session.save(e);
            session.getTransaction().commit();
            session.close();
        }else{
            FacesContext.getCurrentInstance().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_ERROR, "Datos incorrectos", null));
            return "RegistroEstudiante";
        }
    
        return "RegistroDireccion.xhtml";
    }


}


