package Modelo1;
// Generated 1/06/2016 06:42:04 PM by Hibernate Tools 4.3.1



/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private int idPrestador;
     private Integer total;
     private Integer sumParcial;

    public Calificacion() {
    }

	
    public Calificacion(int idPrestador) {
        this.idPrestador = idPrestador;
    }
    public Calificacion(int idPrestador, Integer total, Integer sumParcial) {
       this.idPrestador = idPrestador;
       this.total = total;
       this.sumParcial = sumParcial;
    }
   
    public int getIdPrestador() {
        return this.idPrestador;
    }
    
    public void setIdPrestador(int idPrestador) {
        this.idPrestador = idPrestador;
    }
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }
    public Integer getSumParcial() {
        return this.sumParcial;
    }
    
    public void setSumParcial(Integer sumParcial) {
        this.sumParcial = sumParcial;
    }




}


