package Modelo1;
// Generated 1/06/2016 06:42:04 PM by Hibernate Tools 4.3.1



/**
 * Calificacion generated by hbm2java
 */
public class CalificacionEstudiante  implements java.io.Serializable {

     private int idCalificacion;
     private int idEstudiante;
     private Integer sumP; 
     private Integer numE;

    public int getIdCalificacion() {
        return idCalificacion;
    }

    public void setIdCalificacion(int idCalificacion) {
        this.idCalificacion = idCalificacion;
    }

    public int getIdEstudiante() {
        return idEstudiante;
    }

    public void setIdEstudiante(int idEstudiante) {
        this.idEstudiante = idEstudiante;
    }

    public Integer getSumP() {
        return sumP;
    }

    public void setSumP(Integer sumP) {
        this.sumP = sumP;
    }

    public Integer getNumE() {
        return numE;
    }

    public void setNumE(Integer numE) {
        this.numE = numE;
    }


    public CalificacionEstudiante() {
    }

	
    public CalificacionEstudiante(int idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public CalificacionEstudiante(int idCalificacion,int idEstudiante, Integer sumP, Integer numE) {
       this.idCalificacion = idCalificacion;
       this.idEstudiante = idEstudiante;
       this.sumP= sumP;
       this.numE =numE;
    }
   
   
}


