package Modelo1;
// Generated 13/04/2016 11:24:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DireccionUsuario generated by hbm2java
 */
public class DireccionUsuario  implements java.io.Serializable {


     private int idDireccionU;
     private String paisU;
     private String estadoU;
     private String delegacionU;
     private int codigoPostalU;
     private String calleU;
     private String coloniaU;
     private Set<TieneDireccionU> tieneDireccionUs = new HashSet<TieneDireccionU>(0);

    public DireccionUsuario() {
    }

	
    public DireccionUsuario(int idDireccionU, String paisU, String estadoU, String delegacionU, int codigoPostalU, String calleU, String coloniaU) {
        this.idDireccionU = idDireccionU;
        this.paisU = paisU;
        this.estadoU = estadoU;
        this.delegacionU = delegacionU;
        this.codigoPostalU = codigoPostalU;
        this.calleU = calleU;
        this.coloniaU = coloniaU;
    }
    public DireccionUsuario(int idDireccionU, String paisU, String estadoU, String delegacionU, int codigoPostalU, String calleU, String coloniaU, Set<TieneDireccionU> tieneDireccionUs) {
       this.idDireccionU = idDireccionU;
       this.paisU = paisU;
       this.estadoU = estadoU;
       this.delegacionU = delegacionU;
       this.codigoPostalU = codigoPostalU;
       this.calleU = calleU;
       this.coloniaU = coloniaU;
       this.tieneDireccionUs = tieneDireccionUs;
    }
   
    public int getIdDireccionU() {
        return this.idDireccionU;
    }
    
    public void setIdDireccionU(int idDireccionU) {
        this.idDireccionU = idDireccionU;
    }
    public String getPaisU() {
        return this.paisU;
    }
    
    public void setPaisU(String paisU) {
        this.paisU = paisU;
    }
    public String getEstadoU() {
        return this.estadoU;
    }
    
    public void setEstadoU(String estadoU) {
        this.estadoU = estadoU;
    }
    public String getDelegacionU() {
        return this.delegacionU;
    }
    
    public void setDelegacionU(String delegacionU) {
        this.delegacionU = delegacionU;
    }
    public int getCodigoPostalU() {
        return this.codigoPostalU;
    }
    
    public void setCodigoPostalU(int codigoPostalU) {
        this.codigoPostalU = codigoPostalU;
    }
    public String getCalleU() {
        return this.calleU;
    }
    
    public void setCalleU(String calleU) {
        this.calleU = calleU;
    }
    public String getColoniaU() {
        return this.coloniaU;
    }
    
    public void setColoniaU(String coloniaU) {
        this.coloniaU = coloniaU;
    }
    public Set<TieneDireccionU> getTieneDireccionUs() {
        return this.tieneDireccionUs;
    }
    
    public void setTieneDireccionUs(Set<TieneDireccionU> tieneDireccionUs) {
        this.tieneDireccionUs = tieneDireccionUs;
    }




}


