package Modelo1;
// Generated 13/04/2016 11:24:39 AM by Hibernate Tools 4.3.1



/**
 * TieneContratoU generated by hbm2java
 */
public class TieneContratoU  implements java.io.Serializable {


     private int contrato;
     private Estudiante estudiante;
     private Prestador prestador;

    public TieneContratoU() {
    }

    public TieneContratoU(int contrato, Estudiante estudiante, Prestador prestador) {
       this.contrato = contrato;
       this.estudiante = estudiante;
       this.prestador = prestador;
    }
   
    public int getContrato() {
        return this.contrato;
    }
    
    public void setContrato(int contrato) {
        this.contrato = contrato;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Prestador getPrestador() {
        return this.prestador;
    }
    
    public void setPrestador(Prestador prestador) {
        this.prestador = prestador;
    }




}


