package Modelo1;
// Generated 13/04/2016 11:24:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private int idContrato;
     private Date fechaInicio;
     private Date fechaFin;
     private int idCuarto;
     private Set<TieneEvaluacionC> tieneEvaluacionCs = new HashSet<TieneEvaluacionC>(0);

    public Contrato() {
    }

	
    public Contrato(int idContrato, Date fechaInicio, int idCuarto) {
        this.idContrato = idContrato;
        this.fechaInicio = fechaInicio;
        this.idCuarto = idCuarto;
    }
    public Contrato(int idContrato, Date fechaInicio, Date fechaFin, int idCuarto, Set<TieneEvaluacionC> tieneEvaluacionCs) {
       this.idContrato = idContrato;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.idCuarto = idCuarto;
       this.tieneEvaluacionCs = tieneEvaluacionCs;
    }
   
    public int getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public int getIdCuarto() {
        return this.idCuarto;
    }
    
    public void setIdCuarto(int idCuarto) {
        this.idCuarto = idCuarto;
    }
    public Set<TieneEvaluacionC> getTieneEvaluacionCs() {
        return this.tieneEvaluacionCs;
    }
    
    public void setTieneEvaluacionCs(Set<TieneEvaluacionC> tieneEvaluacionCs) {
        this.tieneEvaluacionCs = tieneEvaluacionCs;
    }




}


