package Modelo1;
// Generated 13/04/2016 11:24:39 AM by Hibernate Tools 4.3.1



/**
 * TieneCuarto generated by hbm2java
 */
public class TieneCuarto  implements java.io.Serializable {


     private int cuarto;
     private Prestador prestador;

    public TieneCuarto() {
    }

    public TieneCuarto(int cuarto, Prestador prestador) {
       this.cuarto = cuarto;
       this.prestador = prestador;
    }
   
    public int getCuarto() {
        return this.cuarto;
    }
    
    public void setCuarto(int cuarto) {
        this.cuarto = cuarto;
    }
    public Prestador getPrestador() {
        return this.prestador;
    }
    
    public void setPrestador(Prestador prestador) {
        this.prestador = prestador;
    }




}


