package Map;
// Generated 12-abr-2016 14:10:40 by Hibernate Tools 4.3.1



/**
 * TieneEvaluacionC generated by hbm2java
 */
public class TieneEvaluacionC  implements java.io.Serializable {


     private int evaluacion;
     private int contrato;

    public TieneEvaluacionC() {
    }

    public TieneEvaluacionC(int evaluacion, int contrato) {
       this.evaluacion = evaluacion;
       this.contrato = contrato;
    }
   
    public int getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(int evaluacion) {
        this.evaluacion = evaluacion;
    }
    public int getContrato() {
        return this.contrato;
    }
    
    public void setContrato(int contrato) {
        this.contrato = contrato;
    }




}


