package Map;
// Generated 12-abr-2016 14:10:40 by Hibernate Tools 4.3.1



/**
 * TieneDireccionC generated by hbm2java
 */
public class TieneDireccionC  implements java.io.Serializable {


     private int cuarto;
     private int direccionC;

    public TieneDireccionC() {
    }

    public TieneDireccionC(int cuarto, int direccionC) {
       this.cuarto = cuarto;
       this.direccionC = direccionC;
    }
   
    public int getCuarto() {
        return this.cuarto;
    }
    
    public void setCuarto(int cuarto) {
        this.cuarto = cuarto;
    }
    public int getDireccionC() {
        return this.direccionC;
    }
    
    public void setDireccionC(int direccionC) {
        this.direccionC = direccionC;
    }




}


