package Map;
// Generated 12-abr-2016 23:56:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DireccionCuarto generated by hbm2java
 */
public class DireccionCuarto  implements java.io.Serializable {


     private int idDireccionC;
     private String delegacionC;
     private int codigoPostalC;
     private String coloniaC;
     private String calleC;
     private String linkUbicacion;
     private Set tieneDireccionCs = new HashSet(0);

    public DireccionCuarto() {
    }

	
    public DireccionCuarto(int idDireccionC, String delegacionC, int codigoPostalC, String coloniaC, String calleC) {
        this.idDireccionC = idDireccionC;
        this.delegacionC = delegacionC;
        this.codigoPostalC = codigoPostalC;
        this.coloniaC = coloniaC;
        this.calleC = calleC;
    }
    public DireccionCuarto(int idDireccionC, String delegacionC, int codigoPostalC, String coloniaC, String calleC, String linkUbicacion, Set tieneDireccionCs) {
       this.idDireccionC = idDireccionC;
       this.delegacionC = delegacionC;
       this.codigoPostalC = codigoPostalC;
       this.coloniaC = coloniaC;
       this.calleC = calleC;
       this.linkUbicacion = linkUbicacion;
       this.tieneDireccionCs = tieneDireccionCs;
    }
   
    public int getIdDireccionC() {
        return this.idDireccionC;
    }
    
    public void setIdDireccionC(int idDireccionC) {
        this.idDireccionC = idDireccionC;
    }
    public String getDelegacionC() {
        return this.delegacionC;
    }
    
    public void setDelegacionC(String delegacionC) {
        this.delegacionC = delegacionC;
    }
    public int getCodigoPostalC() {
        return this.codigoPostalC;
    }
    
    public void setCodigoPostalC(int codigoPostalC) {
        this.codigoPostalC = codigoPostalC;
    }
    public String getColoniaC() {
        return this.coloniaC;
    }
    
    public void setColoniaC(String coloniaC) {
        this.coloniaC = coloniaC;
    }
    public String getCalleC() {
        return this.calleC;
    }
    
    public void setCalleC(String calleC) {
        this.calleC = calleC;
    }
    public String getLinkUbicacion() {
        return this.linkUbicacion;
    }
    
    public void setLinkUbicacion(String linkUbicacion) {
        this.linkUbicacion = linkUbicacion;
    }
    public Set getTieneDireccionCs() {
        return this.tieneDireccionCs;
    }
    
    public void setTieneDireccionCs(Set tieneDireccionCs) {
        this.tieneDireccionCs = tieneDireccionCs;
    }




}


