package Map;
// Generated 12-abr-2016 23:56:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private int idUsuario;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String correo;
     private String telefono;
     private byte[] fotoU;
     private String contrasenya;
     private String facultad;
     private String carrera;
     private Set tieneContratoUs = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(int idUsuario, String nombre, String apellidoPaterno, String apellidoMaterno, String correo, String telefono, String contrasenya, String facultad, String carrera) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.correo = correo;
        this.telefono = telefono;
        this.contrasenya = contrasenya;
        this.facultad = facultad;
        this.carrera = carrera;
    }
    public Estudiante(int idUsuario, String nombre, String apellidoPaterno, String apellidoMaterno, String correo, String telefono, byte[] fotoU, String contrasenya, String facultad, String carrera, Set tieneContratoUs) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.correo = correo;
       this.telefono = telefono;
       this.fotoU = fotoU;
       this.contrasenya = contrasenya;
       this.facultad = facultad;
       this.carrera = carrera;
       this.tieneContratoUs = tieneContratoUs;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public byte[] getFotoU() {
        return this.fotoU;
    }
    
    public void setFotoU(byte[] fotoU) {
        this.fotoU = fotoU;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public Set getTieneContratoUs() {
        return this.tieneContratoUs;
    }
    
    public void setTieneContratoUs(Set tieneContratoUs) {
        this.tieneContratoUs = tieneContratoUs;
    }




}


