package Map;
// Generated 12-abr-2016 23:56:00 by Hibernate Tools 4.3.1



/**
 * TieneEvaluacionC generated by hbm2java
 */
public class TieneEvaluacionC  implements java.io.Serializable {


     private int evaluacion;
     private Contrato contrato;

    public TieneEvaluacionC() {
    }

    public TieneEvaluacionC(int evaluacion, Contrato contrato) {
       this.evaluacion = evaluacion;
       this.contrato = contrato;
    }
   
    public int getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(int evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }




}


